### ISSUE TITLE
Matplotlib backend depreciation warning

### ISSUE THREAD

**Issue by trappitsch** [RIMS-Code/RIMSSchemeDrawer#2]
**`matplotlib`**

Packaging with `fbs` with the most current `matplotlib` version results in the following depreciation warning: 

```console
 -c:12: MatplotlibDeprecationWarning: 
The matplotlib.backends.backend_qt4agg backend was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
```

This happens on Linux, macOS, and Windows. Can either fix the `matplotlib` version in the `requirements.txt` file (ugly) or figure out what new backend to use and test it.

**Comment by trappitsch** [comment]
Unclear why this error actually shows up. Not using `qt4agg` anywhere, everything is written using `qt5agg`... Closing this for now.

**Comment by wondie** [comment]
This warning is gone when I used `backend_qt5agg`.

**Comment by trappitsch** [comment]
Thanks @wondie, reopening this to check it out. Your comment is much appreciated!

**Comment by trappitsch** [comment]
I'm also using `backend_qt5agg` everywhere. I'm wondering if packaging w/ `fbs` packages the qt4 backend as well, which triggers the warning?
